### ISSUE TITLE
Repo marked as ineligible in Hacktoberfest

### ISSUE THREAD

**Issue by the-it-weirdo** [nb2998/DS_Algo#177]
Hello, Maintainer(s),
This repo is marked as ineligible in DigitalOcean's Hacktoberfest 2020. Please add the topic 'hacktoberfest' to this repo.
I am attaching an image for reference.
![Screenshot (1023)](https://user-images.githubusercontent.com/52004561/95009020-4af05180-063c-11eb-8fbc-d4b9c22ff776.png)

**Comment by shaw8wit** [comment]
I support this :+1:

**Comment by nb2998** [comment]
@the-it-weirdo Thanks for letting me know, could you please recheck now?

**Comment by the-it-weirdo** [comment]
@nb2998 Yes. Thank you. It's okay now.
