### ISSUE TITLE
Refactoring the packages (algos)

### ISSUE THREAD

**Issue by nb2998** [nb2998/DS_Algo#35]
Create specific packages inside algos
Eg: algos/DP, algos/Graphs, algos/Arrays etc.

[Do not make changes to any code in the pull request for this issue]

**Comment by lass7965** [comment]
Should anything be moved into these packages, or should they be left empty?
Furthermore are those the 3 packages you want?

**Comment by nb2998** [comment]
@lass7965 They should be left empty as of now. I'll create a separate issue for that. 
Regarding the number of packages, as many as you can think of and are relevant. No fixed number.
